### ISSUE TITLE
How to save the suffix table and reload it later?

### ISSUE THREAD

**Issue by HugoLaurencon** [BurntSushi/suffix#17]
Hello,
Could you explain to a non-Rust developer how you would save the suffix table once computed, to be able to re-use later?
Thanks!

**Comment by BurntSushi** [comment]
Thanks for asking this!

This is indeed possible. You would
use SuffixTable::into_parts[1] to to get your &str (original text) and
&[u32] (the suffix array). You can then serialize them however you
choose. The former can written trivially as a &[u8]. The latter I
would probably write using something like ByteOrder::write_u32_into[2]
to convert your &[u32] to an endian specific representation in &[u8]
form, and then write the &[u8] directly. To deserialize, you'd do the
inverse operations using ByteOrder::read_u32_into[3] and
SuffixTable::from_parts[4].

The crate docs don't show an example of serialization because it's
really beyond its scope, and it exposes its underlying primitive
representation enough that it easily devolves into a self-contained
"how do I do this in Rust" problem. If I had more time it would be
worth adding examples to the docs, but I'm also kind of miffed on the
whole suffix array thing. I wrote that crate but I have yet to find a
good use case for it.

[1]: https://docs.rs/suffix/latest/suffix/struct.SuffixTable.html#method.into_parts
[2]: https://docs.rs/byteorder/latest/byteorder/trait.ByteOrder.html#tymethod.write_u32_into
[3]: https://docs.rs/byteorder/latest/byteorder/trait.ByteOrder.html#tymethod.read_u32_into
[4]: https://docs.rs/suffix/latest/suffix/struct.SuffixTable.html#method.from_parts
